# Generated by Django 3.2.25 on 2024-09-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withFriends', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userScore', models.IntegerField(default=0)),
                ('otherScore', models.IntegerField(default=0)),
                ('opponent', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_url', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('pseudo', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('wallet', models.BigIntegerField()),
                ('pool_year', models.BigIntegerField()),
                ('image', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('id42', models.IntegerField(default=0)),
                ('connected', models.BooleanField(default=False)),
                ('chatId', models.IntegerField(default=0)),
                ('TourName', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('GameHistory', models.ManyToManyField(blank=True, related_name='game_history', to='app.UserHistory')),
                ('blocked', models.ManyToManyField(blank=True, related_name='_app_user42_blocked_+', to='app.User42')),
                ('userFriends', models.ManyToManyField(blank=True, related_name='_app_user42_userFriends_+', to='app.User42')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('player_count', models.IntegerField(default=0)),
                ('disconnect', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentGameRoom', to='app.gameroom')),
                ('players', models.ManyToManyField(blank=True, related_name='TournamentPlayers', to='app.User42')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user42')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.chatgroup')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='app.user42'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='app.user42'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='app.user42')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='app.user42')),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to='app.User42')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User42', to='app.user42')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='app.user42')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='app.user42')),
            ],
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='authors',
            field=models.ManyToManyField(related_name='chat_groups', to='app.User42'),
        ),
    ]
